# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20161123_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='title',
        ),
    ]
