"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.dirname(BASE_DIR)

INTERNAL_IPS = ('127.0.0.1',)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q1c)hwyp(()8c6%)_*9y22p157r6y3d2@)m=1u357ug#9qo*)s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
ALLOWED_HOSTS = ['.chadomarket.ru']

TEMPLATE_DEBUG = DEBUG
# THUMBNAIL_DEBUG = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'registration',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.flatpages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django.contrib.gis',
    'django.contrib.humanize',
    'django.contrib.postgres.search',
    'django.contrib.sitemaps',
    'django_rq',
    # Three-part library
    'htmlmin',
    'compressor',
    'extra_views',
    'sorl.thumbnail',
    'password_reset',
    'mptt',
    'rest_framework',
    'widget_tweaks',
    'django_mptt_admin',
    'corsheaders',
    # custom apps
    'common',
    'core',
    'news',
    'checkout',
    'address',
    'shipping',
    'catalogue',
    'catalogue.reviews',
    'partner',
    'basket',
    'order',
    'seo',
    'wishlists',
    'customer',
    'offer',
    'voucher',
    'comparelists',
    'api',
    'parsers',
    'robots',
    'payment',
    'ordermanagerwallet',
    'exchange_to_site',
    'articles',
    'hitcount',

]


MIDDLEWARE = [
    # 'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'htmlmin.middleware.HtmlMinifyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
    # 'htmlmin.middleware.MarkRequestMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'basket.middleware.BasketMiddleware',
    'common.middleware.SimpleMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'call_centr.middleware.HeaderCountersMiddleware'
]

ROOT_URLCONF = 'store.urls'

TINYMCE_DEFAULT_CONFIG = {
     'plugins': "table,spellchecker,paste,searchreplace,directionality",
     'theme': "advanced",
     'cleanup_on_startup': True,
     'custom_undo_redo_levels': 10,
     'theme_advanced_resizing': "true",
     'resize': "both",
     'file_browser_callback': 'mce_filebrowser'

 }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(ROOT_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.contrib.auth.context_processors.auth',
                # Наш контекстный процессор для соц сетей
                'common.context_processors.geo_city',
                'common.context_processors.get_current_path',
                'common.context_processors.get_promo_discount',
                'common.context_processors.get_main_categories',
                'soclinks.processor.soclink',
                'call_centr.context_processors.call_orders'
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


DATABASES = {
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 5,
        }
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-RU'


TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(ROOT_DIR, 'static')
MEDIA_ROOT = os.path.join(ROOT_DIR, 'media')

STATICFILES_DIRS = (
    os.path.join(ROOT_DIR, 'assets'),
)

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

AUTH_USER_MODEL = 'customer.User'
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/users/login/'

SITE_ID = 1

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://127.0.0.1:8983/solr/',
        'INCLUDE_SPELLING': True
    },
}
CART_PRODUCT_MODEL = 'products.models.Product'
OSCAR_IMAGE_FOLDER = 'images/products/%Y/%m/'
OSCAR_SLUG_ALLOW_UNICODE = False
OSCAR_DELETE_IMAGE_FILES = True
OSCAR_DEFAULT_CURRENCY = 'RUB'

gettext_noop = lambda s: s

LANGUAGES = (
    ('ru', gettext_noop('Russian')),
    ('en-gb', gettext_noop('British English')),
)
OSCAR_REQUIRED_ADDRESS_FIELDS = ('first_name', 'last_name', 'line1',
                                 'line4', 'postcode', 'country')
OSCAR_EAGER_ALERTS = True

OSCAR_BASKET_COOKIE_LIFETIME = 7 * 24 * 60 * 60
OSCAR_BASKET_COOKIE_OPEN = 'oscar_open_basket'
OSCAR_BASKET_COOKIE_SECURE = False
OSCAR_MAX_BASKET_QUANTITY_THRESHOLD = 10000
ORDER_SUM_FOR_FREE_SHIP = 2000

OSCAR_HIDDEN_FEATURES = []
OSCAR_MISSING_IMAGE_URL = 'image_not_found.jpg'

# тестовые точно рабочие данные
SPSR_LOGIN = 'Chadomarket'
SPSR_PASSW = 'jf7HjUv'
SPSR_URL = 'https://3pl.spsr.ru/webapi/sc/execute'
SPSR_EX_LOGIN = '7702614911CHA'
SPSR_EX_PASSW = 'hh56IC'
SPSR_EX_IKN = '7702614911'
SPSR_EX_URL = 'https://api.spsr.ru/'
PICKPOINT_URL = 'http://pickpoint.ru/postamats.xml'
# required params in template below. option params are handling by constructor(get_string param).
SPSR_EX_CALC_URL = 'http://spsr.ru/tarifcalc/'

DPD_EX_LOGIN = '358811ru'
DPD_EX_PASSW = 'UWL1WC'
DPD_EX_IKN = '1001044399'
DPD_INT_KEY = 'CEEC815BFC1A49E4D29B12ABD20C96EA619BA809'
DPD_EX_IKN_TEST = '1001027795'
DPD_INT_KEY_TEST = '182A17BD6FC5557D1FCA30FA1D56593EB21AEF88'
ADDITIONAL_DAYS = 1

OSCAR_DASHBOARD_NAVIGATION = [
    {
        'label': 'Dashboard',
        'icon': 'icon-th-list',
        'url_name': 'dashboard:index',
    },
    {
        'label': 'Каталог',
        'icon': 'icon-sitemap',
        'children': [
            {
                'label': 'Продукты',
                'url_name': 'dashboard:catalogue-product-list',
            },

            {
                'label': 'Категории',
                'url_name': 'dashboard:catalogue-category-list',
            },
        ]
    },
    {
        'label': 'Пользователи',
        'icon': 'icon-group',
    },
    {
        'label': 'Предложения',
        'icon': 'icon-bullhorn',
    },
]
OSCAR_DASHBOARD_DEFAULT_ACCESS_FUNCTION = 'dashboard.nav.default_access_fn'  # noqa
OSCAR_ACCOUNTS_REDIRECT_URL = 'customer:profile-view'

OSCAR_ALLOW_ANON_REVIEWS = True
OSCAR_MODERATE_REVIEWS = True

# GEOIP_LIBRARY_PATH = '/usr/local/Cellar/geoip/1.6.9/bin/geoiplookup'
GEOIP_PATH = os.path.join(ROOT_DIR, 'geoip2')
# GEOIP_PATH = os.path.join(MEDIA_ROOT, 'geoip')
GEOIP_COUNTRY = 'GeoLite2-Country.mmdb'
GEOIP_CITY = 'GeoLite2-City.mmdb'

REGISTRATION_FORM = 'customer.forms.CustomerRegistrationForm'

OSCAR_SLUG_FUNCTION = 'core.utils.default_slugifier'
OSCAR_SLUG_MAP = {}
OSCAR_SLUG_BLACKLIST = []

# Recently-viewed products
OSCAR_RECENTLY_VIEWED_COOKIE_LIFETIME = 7 * 24 * 60 * 60
OSCAR_RECENTLY_VIEWED_COOKIE_NAME = 'oscar_history'
OSCAR_RECENTLY_VIEWED_COOKIE_SECURE = False
OSCAR_RECENTLY_VIEWED_PRODUCTS = 20

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    #
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    #     # 'rest_framework.permissions.DjangoModelPermissions',
    # ],

    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': (
        # 'rest_framework_filters.backends.DjangoFilterBackend',
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}


FROM_EMAIL = 'stranger1@zYzXzzaCojAW.localdomain'

RQ_QUEUES = {
     'default': {
     'HOST': 'localhost',
     'PORT': 6379,
     'DB': 8,
     },
}


PRIVATE_FILE = os.path.join(ROOT_DIR, 'private.key')
CERT_FILE = os.path.join(ROOT_DIR, '121328.cer')

DEFAULT_FROM_EMAIL = 'no-reply@chadomarket.ru'
X_FRAME_OPTIONS = 'DENY'

CORS_ORIGIN_ALLOW_ALL = True

CSRF_TRUSTED_ORIGINS = (
    '*.webvisor.com',
    '*.yandex.net',
)

#THUMBNAIL_COLORSPACE = None
THUMBNAIL_PRESERVE_FORMAT = True

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
# HTML_MINIFY = True
# EXCLUDE_FROM_MINIFYING = ('^ordermanagerwallet/', '^admin/', '^callcentr/')
COMPRESS_ENABLED=True
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter',  'compressor.filters.cssmin.CSSMinFilter']
DATA_UPLOAD_MAX_NUMBER_FIELDS = None

FILEBROWSER_DIRECTORY = ''
DIRECTORY = ''

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            # 'uploadsloadwidget',
            # 'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'uploadwidget',
        ]),
    }
}
