# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
