# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_1c_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
