# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_product_1c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
