# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_category_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(default=0)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalogue.Category')),
            ],
        ),
    ]
