# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
    ]
