# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, verbose_name='Slug'),
        ),
    ]
