# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20161115_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_mrc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
