# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_product_price_mrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
