# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_product_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveSmallIntegerField(default=0)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_gifts', to='catalogue.Product')),
            ],
            options={
                'verbose_name_plural': 'Подарки к товару',
                'ordering': ['primary', '-ranking'],
                'verbose_name': 'Подарок к товару',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productgift',
            unique_together=set([('primary', 'gift')]),
        ),
    ]
