# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20161124_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgift',
            options={'ordering': ['primary_gift', '-ranking'], 'verbose_name': 'Подарок к товару', 'verbose_name_plural': 'Подарки к товару'},
        ),
        migrations.RenameField(
            model_name='productgift',
            old_name='primary',
            new_name='primary_gift',
        ),
        migrations.AddField(
            model_name='product',
            name='gift_products',
            field=models.ManyToManyField(blank=True, related_name='products_gifts', through='catalogue.ProductGift', to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalogue.Product', verbose_name='Recommended product'),
        ),
        migrations.AlterUniqueTogether(
            name='productgift',
            unique_together=set([('primary_gift', 'gift')]),
        ),
    ]
