# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20161124_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Recommended product'),
        ),
    ]
