# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20161125_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
