# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_product_artikul'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логотип бренда'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Rating'),
        ),
    ]
