# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20161206_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Категория в меню', 'verbose_name_plural': 'Категории в меню'},
        ),
    ]
