# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20161208_0852'),
        ('catalogue', '0020_brand'),
    ]

    operations = [
    ]
