# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_merge_20161212_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('show', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='FilterItemValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True)),
                ('value_integer', models.IntegerField(null=True)),
                ('position', models.IntegerField()),
                ('filter_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_item_values', to='catalogue.FilterItem')),
            ],
        ),
    ]
