# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_filteritem_filteritemvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_logo',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.Brand'),
        ),
    ]
