# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20161216_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, 'Унисекс'), (1, 'Для мальчиков'), (2, 'Для девочек')], default=0, verbose_name='Пол'),
        ),
    ]
