# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_exchange', '0002_street'),
        ('catalogue', '0025_auto_20161218_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Address')),
                ('fio', models.CharField(db_index=True, max_length=255, verbose_name='FIO')),
                ('organization', models.CharField(db_index=True, max_length=255, verbose_name='Organization')),
                ('phone', models.CharField(db_index=True, max_length=255, verbose_name='Phone')),
                ('additional_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional comment')),
                ('post_code', models.CharField(db_index=True, max_length=255, verbose_name='Post code')),
                ('address_type', models.IntegerField(default=8, verbose_name='address type')),
                ('sbor_addr_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='ID address')),
                ('sbor_addr_owner_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='Owner Id address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics_exchange.City')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
