# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_contractorcatalogue'),
        ('catalogue', '0025_auto_20161221_1712'),
    ]

    operations = [
    ]
