# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20161222_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorcatalogue',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_contractor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_contractor_label',
        ),
    ]
