# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20161222_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcatalogue',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_contractor', to='catalogue.ContractorCatalogue'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contractor_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contractor Label'),
        ),
    ]
