# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_auto_20161222_2102'),
        ('catalogue', '0027_merge_20161222_0722'),
    ]

    operations = [
    ]
