# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-29 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20161228_1947'),
        ('catalogue', '0032_product_video_container'),
    ]

    operations = [
    ]
