# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_merge_20161229_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_container',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
