# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20170104_1436'),
        ('catalogue', '0033_merge_20161230_0620'),
    ]

    operations = [
    ]
