# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_merge_20161222_0212'),
        ('catalogue', '0036_auto_20170116_1602'),
    ]

    operations = [
    ]
