# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_merge_20170116_2009'),
        ('catalogue', '0037_auto_20170117_1029'),
    ]

    operations = [
    ]
