# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_merge_20170118_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_main',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_main',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.FloatField(blank=True, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_main',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_main',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.Brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота(транспортная)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина(транспортная)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Сокращенное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес(транспортный)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина(транспортная)'),
        ),
    ]
