# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20170119_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Материал'),
        ),
    ]
