# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0040_auto_20170119_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_main_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип веса'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_trans_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип веса(транспортный)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wlh_main_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип размеров (ДхШхВ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wlh_trans_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип размеров транс.(ДхШхВ)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img_good_pk',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
