# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_auto_20170313_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set([]),
        ),
    ]
