# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_contractorcatalogue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_name_original',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название в оригинале'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name_ru',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_i',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название в именительном падеже'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_p',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название в предложном падеже'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_r',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название в родительном падеже'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_v',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='Название в винительном падеже'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название в именительном падеже'),
        ),
    ]
