# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0045_auto_20170516_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name_original',
            new_name='name_original',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name_i',
            new_name='name_i',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name_p',
            new_name='name_p',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name_r',
            new_name='name_r',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name_v',
            new_name='name_v',
        ),
    ]
