# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_brand_name_ru_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_plural',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название во множественном числе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_i',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название в именительном падеже'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_p',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название в предложном падеже'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_r',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название в родительном падеже'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_v',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название в винительном падеже'),
        ),
    ]
