# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0048_auto_20170524_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_plural_r',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Название во множественном числе в родительном падеже'),
        ),
    ]
