# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_category_name_plural_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_accessory',
            field=models.BooleanField(default=False),
        ),
    ]
