# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0053_auto_20170620_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='driver_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Забрал'), (2, 'Отменен'), (3, 'Перенесен')], default=0, verbose_name='Статус водителя'),
        ),
    ]
