# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_auto_20170621_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.ProductAttribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
            options={
                'verbose_name_plural': 'Атрибуты/Категории',
                'ordering': ['attribute', 'category'],
                'verbose_name': 'Атрибуты/Категории',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productattributecategory',
            unique_together=set([('attribute', 'category')]),
        ),
    ]
