# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-23 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0054_product_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
    ]
