# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_product_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
