# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0055_auto_20170622_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_color_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
