# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0056_auto_20170707_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeoption',
            name='maximum',
            field=models.FloatField(default=0.0, help_text='Сейчас используется только для размеров', verbose_name='Значение до'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='minimum',
            field=models.FloatField(default=0.0, help_text='Сейчас используется только для размеров', verbose_name='Значение от'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='show_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
