# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0057_auto_20170710_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
