# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0058_auto_20170724_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeoption',
            name='case_i',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_mi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_mr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_r',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_v',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
