# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_auto_20170801_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='name_show',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название отображаемое на сайте'),
        ),
    ]
