# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0059_auto_20170901_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='move_reason',
            field=models.TextField(blank=True, verbose_name='Причина переноса'),
        ),
    ]
