# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_product_move_reason'),
        ('catalogue', '0060_productattribute_name_show'),
    ]

    operations = [
    ]
