# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0060_auto_20170718_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='id_attribute_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
