# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-19 16:30
from __future__ import unicode_literals

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0061_merge_20170904_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='driver_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Забрал'), (2, 'Отменен'), (3, 'Перенесен'), (4, 'Удален')], default=0, verbose_name='Статус водителя'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='code',
            field=models.SlugField(max_length=128, validators=[django.core.validators.RegexValidator(message="Code can only contain the letters a-z, A-Z, digits, and underscores, and can't start with a digit.", regex='^[a-zA-Z_][0-9a-zA-Z_-]*$'), core.validators.non_python_keyword], verbose_name='Code'),
        ),
    ]
