# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0062_auto_20170724_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='category',
            field=models.ManyToManyField(related_name='attributes', through='catalogue.ProductAttributeCategory', to='catalogue.Category'),
        ),
    ]
