# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0063_auto_20170724_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
