# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0064_productattribute_is_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['display_order'], 'verbose_name': 'Атрибут продукта', 'verbose_name_plural': 'Атрибуты продуктов'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
