# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0065_auto_20170804_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_allocated',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number allocated'),
        ),
    ]
