# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0068_auto_20170807_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='color_code',
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='color_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
