# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0069_auto_20170807_1704'),
        ('catalogue', '0060_productattribute_name_show'),
    ]

    operations = [
    ]
