# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0070_merge_20170808_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeoption',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
