# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-14 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0073_auto_20170908_1436'),
        ('catalogue', '0061_merge_20170904_1725'),
    ]

    operations = [
    ]
