# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0074_auto_20170913_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_opt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оптовая Цена'),
        ),
    ]
