# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0062_auto_20170919_1930'),
        ('catalogue', '0076_auto_20170918_1440'),
    ]

    operations = [
    ]
