# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-25 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0078_auto_20170920_1804'),
        ('catalogue', '0074_auto_20170913_0924'),
    ]

    operations = [
    ]
