# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0079_merge_20170925_1157'),
        ('catalogue', '0075_product_price_opt'),
    ]

    operations = [
    ]
