# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-12 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0080_product_old_slug'),
        ('catalogue', '0080_merge_20171003_1600'),
    ]

    operations = [
    ]
