# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0080_product_old_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender_seo',
            field=models.SmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], default=0, verbose_name='Род'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_d',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В дательном падеже'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_md',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Во множественном числе дат. падеже'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_mp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Во множественном числе пред. падеже'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_mt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Во множественном числе твор. падеже'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_mv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Во множественном числе вин. падеже'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_t',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В творительном падеже'),
        ),
    ]
