# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-16 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0081_merge_20171012_1528'),
        ('catalogue', '0082_auto_20171013_1236'),
    ]

    operations = [
    ]
