# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0083_merge_20171016_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
