# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0084_auto_20171024_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer_code',
            field=models.CharField(blank=True, help_text='Используется для фида Google', max_length=150, null=True, verbose_name='Код потавщика'),
        ),
    ]
