# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0086_merge_20171024_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_slug',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Старый slug товара(для редиректа со старого url на новый)'),
        ),
    ]
