# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0087_auto_20171031_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand_slug_bottom',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Слаг для нижнего изображения'),
        ),
        migrations.AddField(
            model_name='category',
            name='brand_slug_top',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Слаг для верхнего изображения'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_bottom',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_top',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories'),
        ),
    ]
