# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-31 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0087_auto_20171031_1219'),
        ('catalogue', '0087_auto_20171031_1526'),
    ]

    operations = [
    ]
