# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0088_auto_20171102_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brand_slug_bottom',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Слаг для нижнего изображения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brand_slug_top',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Слаг для верхнего изображения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_bottom',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories', verbose_name='Нижнее изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_top',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='categories', verbose_name='Врехнее изображение'),
        ),
    ]
