# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-01 16:13
from __future__ import unicode_literals

import core_models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0089_product_is_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_main_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_trans_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wlh_main_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wlh_trans_type',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.Product', verbose_name='Parent product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=core_models.fields.NullCharField(max_length=64, unique=True, verbose_name='UPC'),
        ),
    ]
