# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0090_auto_20171101_1913'),
        ('catalogue', '0089_auto_20171102_1637'),
    ]

    operations = [
    ]
