# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0091_merge_20171102_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='catalogue.ProductAttributeValue', to='catalogue.ProductAttribute', verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_options',
            field=models.ManyToManyField(blank=True, to='catalogue.Option', verbose_name='Product options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, through='catalogue.ProductRecommendation', to='catalogue.Product', verbose_name='Recommended products'),
        ),
    ]
