# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0091_merge_20171102_1728'),
        ('catalogue', '0087_auto_20171026_1628'),
    ]

    operations = [
    ]
