# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0092_auto_20171108_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattributesimilar',
            name='category_similar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_attributes', to='catalogue.Category'),
        ),
    ]
