# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-08 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0092_auto_20171107_1801'),
        ('catalogue', '0092_merge_20171107_1039'),
    ]

    operations = [
    ]
