# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0092_auto_20171107_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assortment',
            field=models.BooleanField(default=False),
        ),
    ]
