# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0093_merge_20171108_1049'),
        ('catalogue', '0093_product_assortment'),
    ]

    operations = [
    ]
