# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-08 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0093_auto_20171108_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryattributesimilar',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='categoryattributesimilar',
            name='attribute_similar',
        ),
        migrations.RemoveField(
            model_name='categoryattributesimilar',
            name='category_similar',
        ),
        migrations.DeleteModel(
            name='CategoryAttributeSimilar',
        ),
    ]
