# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0093_product_assortment'),
        ('catalogue', '0092_auto_20171107_1747'),
    ]

    operations = [
    ]
