# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0094_merge_20171110_1647'),
        ('catalogue', '0094_merge_20171110_1234'),
    ]

    operations = [
    ]
