# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0094_auto_20171108_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'ordering': ['primary', 'ranking'], 'verbose_name': 'Product recommendation', 'verbose_name_plural': 'Product recomendations'},
        ),
    ]
