# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-14 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0096_contractorcatalogue_cm_code'),
        ('catalogue', '0095_auto_20171114_1633'),
    ]

    operations = [
    ]
