# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0098_auto_20171116_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributeoption',
            old_name='case_md',
            new_name='case_d_m',
        ),
        migrations.RenameField(
            model_name='productattributeoption',
            old_name='case_mi',
            new_name='case_i_m',
        ),
        migrations.RenameField(
            model_name='productattributeoption',
            old_name='case_mp',
            new_name='case_p_m',
        ),
        migrations.RenameField(
            model_name='productattributeoption',
            old_name='case_mr',
            new_name='case_r_m',
        ),
        migrations.RenameField(
            model_name='productattributeoption',
            old_name='case_mt',
            new_name='case_t_m',
        ),
        migrations.RenameField(
            model_name='productattributeoption',
            old_name='case_mv',
            new_name='case_v_m',
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_d_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В дательном падеже в среднем роде'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_i_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В именительном падеже в среднем роде'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_noun',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Существительное'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_p_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В предложном падеже в среднем роде'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_r_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В родительном падеже в среднем роде'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_t_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В творительном падеже в среднем роде'),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='case_v_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В винительном падеже в среднем роде'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender_seo',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('it', 'Средний'), ('plural', 'Множественное число')], default='male', max_length=50, verbose_name='Род/Число'),
        ),
    ]
