# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0099_auto_20171117_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
