# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_exchange', '0002_street'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='status name')),
                ('display_name', models.CharField(default='', max_length=128)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='status name')),
            ],
            options={
                'verbose_name': 'Order Payment Status',
                'verbose_name_plural': 'Order Payment Statuses',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='payment type name')),
            ],
            options={
                'verbose_name': 'Типы олпаты',
                'verbose_name_plural': 'Типы олпаты',
            },
        ),
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Order Shipment method',
                'verbose_name_plural': 'Order Shipment method',
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='status name')),
            ],
            options={
                'verbose_name': 'Order Shipment Status',
                'verbose_name_plural': 'Order Shipment Statuses',
            },
        ),
        migrations.CreateModel(
            name='Spsr_PO_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('status_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spsr_po_status', to='order.OrderStatus')),
            ],
            options={
                'verbose_name': 'SPSR Purchase Order Status',
                'verbose_name_plural': 'SPSR Purchaseø Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='Spsr_SO_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('status_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spsr_so_status', to='order.OrderStatus')),
            ],
            options={
                'verbose_name': 'SPSR Sales Order Status',
                'verbose_name_plural': 'SPSR Sales Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='StatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['pk'], 'verbose_name': 'Строка заказа', 'verbose_name_plural': 'Строки заказа'},
        ),
        migrations.AlterModelOptions(
            name='lineattribute',
            options={'verbose_name': 'Атрибут строки заказа', 'verbose_name_plural': 'Атрибуты строк заказа'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_placed'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'verbose_name': 'Заметка о заказе', 'verbose_name_plural': 'Заметки о заказах'},
        ),
        migrations.AddField(
            model_name='line',
            name='comment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='info_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Undone', 'Undone'), ('Rework', 'Rework')], default='Undone', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='call_st',
            field=models.BooleanField(default=False, verbose_name='Call Centr status'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='Default', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_check_po',
            field=models.BooleanField(default=False, verbose_name='Check po needded'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_check_so',
            field=models.BooleanField(default=False, verbose_name='Check so needded'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_mail',
            field=models.BooleanField(default=True, verbose_name='Is need mail to contractor'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_purchase_order',
            field=models.BooleanField(default=False, verbose_name='Is need purchase order'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_sales_order',
            field=models.BooleanField(default=False, verbose_name='Is need sales order'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_exchange.Office'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_order_placed',
            field=models.BooleanField(default=False, verbose_name='Purchase order placed'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_order_placed',
            field=models.BooleanField(default=False, verbose_name='Sales order placed'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='type',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Postoffice', 'Postoffice')], default='Postoffice', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShipmentMethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.OrderStatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='order.StatusGroup'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.PaymentStatus', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.PaymentType', verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShipmentStatus', verbose_name='Shipment Status'),
        ),
    ]
