# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20161230_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='info_status',
            field=models.CharField(choices=[('done', 'Обработан'), ('undone', 'Не обработан'), ('rework', 'Отложен')], default='undone', max_length=50),
        ),
    ]
