# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170111_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='stock_availability',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('custom', 'Под заказ')], max_length=10, null=True),
        ),
    ]
