# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_line_stock_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='info_status',
            field=models.CharField(choices=[('new', 'Новый'), ('remove', 'Удален')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShipmentMethod'),
        ),
    ]
