# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20170119_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='info_status',
            field=models.CharField(choices=[('default', 'По умолчанию'), ('new', 'Новый'), ('remove', 'Удален')], default='default', max_length=50),
        ),
    ]
