# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20170119_1551'),
        ('order', '0006_auto_20170119_2254'),
    ]

    operations = [
    ]
