# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_20170120_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Причина перезвона',
                'verbose_name_plural': 'Причины перезвона',
            },
        ),
        migrations.CreateModel(
            name='RecallReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Причина перезвона',
                'verbose_name_plural': 'Причины перезвона',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='call_centr_status',
            field=models.CharField(blank=True, choices=[('confirm', 'Подтвержден'), ('recall', 'Перезвонить'), ('cancel', 'Отменен')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment_operator_call_centr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recall_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recall_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShipmentStatus', verbose_name='Shipment Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.CancelReason'),
        ),
        migrations.AddField(
            model_name='order',
            name='recall_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.RecallReason'),
        ),
    ]
