# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170126_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelreason',
            options={'verbose_name': 'Причина отмены', 'verbose_name_plural': 'Причины отмена'},
        ),
    ]
