# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170126_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelreason',
            options={'verbose_name': 'Причина отмены', 'verbose_name_plural': 'Причины отмена'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_range',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
