# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170130_0634'),
        ('order', '0009_auto_20170127_1533'),
    ]

    operations = [
    ]
