# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_merge_20170130_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
