# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20170204_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='busy_status',
            field=models.BooleanField(default=False),
        ),
    ]
