# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_busy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_callcentr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
