# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_phone_callcentr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
