# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='quantity_undelivered',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Quantity_Undelivered'),
        ),
    ]
