# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_line_quantity_undelivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
