# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_changeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_lines', to='order.Order', verbose_name='Заказ'),
        ),
    ]
