# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20170331_1523'),
        ('order', '0023_auto_20170331_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('price_opt_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_mrc_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_product_lines', to='order.Line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_double_product_lines', to='catalogue.ContractorCatalogue')),
            ],
            options={
                'verbose_name': 'Строка заказа для дублей',
                'verbose_name_plural': 'Строки заказа для дублей',
            },
        ),
    ]
