# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_doubleproductline'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleproductline',
            name='product_contractor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
