# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-15 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_doubleproductline_product_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='procure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
