# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_procure_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Готов к отправке'), (2, 'Проблемный'), (3, 'Перенесен'), (4, 'В процессе сбора'), (5, 'Сдан в логистическую компанию'), (6, 'Снят с доставки')], default=0, verbose_name='Статус водителя'),
        ),
    ]
