# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-25 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_driver_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='driver_status',
            new_name='order_driver_status',
        ),
    ]
