# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20170825_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_driver_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='procure_datetime',
        ),
    ]
