# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_auto_20170831_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_driver_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Готов к отправке'), (2, 'Проблемный'), (3, 'Перенесен'), (4, 'В процессе сборки'), (5, 'Сдан в логистическую компанию'), (6, 'Снят с доставки')], default=0, verbose_name='Статус водителя'),
        ),
        migrations.AddField(
            model_name='order',
            name='procure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
