# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_dpd_nomen'),
        ('order', '0030_auto_20170901_1655'),
    ]

    operations = [
    ]
