# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-18 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_order_order_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_id_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics_exchange.OfficePickPoint'),
        ),
    ]
