# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_order_order_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dpd_received',
            field=models.BooleanField(default=False),
        ),
    ]
