# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_auto_20170918_1440'),
        ('order', '0033_order_is_dpd_received'),
    ]

    operations = [
    ]
