# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_merge_20170920_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='line',
            name='driver_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Забрал'), (2, 'Отменен'), (3, 'Перенесен'), (4, 'Удален')], default=0, verbose_name='Статус водителя'),
        ),
        migrations.AddField(
            model_name='line',
            name='move_reason',
            field=models.TextField(blank=True, verbose_name='Причина переноса'),
        ),
    ]
