# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-02 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20170920_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='City Id'),
        ),
    ]
