# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_shippingaddress_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='City Id'),
        ),
    ]
