# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_order_order_move_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'У водителя'), (2, 'В кассе')], default=0, verbose_name='Статус денег'),
        ),
    ]
