# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_shippingaddress_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='unit_opt_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Закупочная цена товара'),
        ),
    ]
