# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-09 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20171004_1934'),
        ('order', '0037_order_money_status'),
    ]

    operations = [
    ]
