# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-11 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20171004_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics_exchange.Office'),
        ),
    ]
