# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_merge_20171009_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'В DPD'), (2, 'Своими силами')], default=0, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_driver_status',
            field=models.SmallIntegerField(choices=[(0, 'Нет'), (1, 'Готов к отправке'), (2, 'Проблемный'), (3, 'Перенесен'), (4, 'В процессе сборки'), (5, 'Сдан в логистическую компанию'), (6, 'Снят с доставки'), (7, 'Заказ доставлен, оплачен')], default=0, verbose_name='Статус водителя'),
        ),
    ]
