# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-11 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20171011_1023'),
        ('order', '0039_auto_20171009_1528'),
    ]

    operations = [
    ]
