# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-12 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_merge_20171005_1733'),
        ('order', '0040_merge_20171011_1129'),
    ]

    operations = [
    ]
