# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_merge_20171012_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='unit_price_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена товара со скидкой'),
        ),
    ]
