# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-18 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_line_unit_price_with_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_move_reason',
        ),
    ]
