# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20171101_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_need_check_po',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_need_check_so',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_need_mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_need_purchase_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_need_sales_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_order_placed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sales_order_placed',
        ),
        migrations.AddField(
            model_name='order',
            name='date_delivery_status',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
