# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20171113_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_from_callcenter',
            field=models.BooleanField(default=False, verbose_name='Заказ сделан через колл центр'),
        ),
    ]
