# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_order_order_from_callcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery_status',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
