# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_auto_20171121_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Сумма скидки по промокоду'),
        ),
    ]
