# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-12 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_order_promo_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dalivery_time_interval',
            field=models.CharField(blank=True, choices=[('9-18', '9.00-18.00'), ('9-14', '9.00-14.00'), ('13-18', '13.00-18.00'), ('9-22', '9.00-22.00'), ('18-22', '18.00-22.00 (доп. оплата)')], max_length=30, null=True),
        ),
    ]
