# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0049_order_promo_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='quantity_from_chado_storage',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товаров со склада'),
        ),
    ]
