# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-17 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_order_dalivery_time_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dalivery_time_interval',
            new_name='delivery_time_interval',
        ),
    ]
