# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_remove_order_delivery_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя покупателя(если заказ в один клик)'),
        ),
    ]
