# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('callcenter', 'Заказ из колл центра'), ('basket', 'Заказа из корзины'), ('oneclick', 'Заказ в один клик')], default='basket', max_length=30),
        ),
    ]
