# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_line_quantity_from_chado_storage'),
        ('order', '0054_order_type'),
    ]

    operations = [
    ]
