# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-14 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_merge_20180206_1129'),
        ('order', '0055_merge_20180202_1752'),
    ]

    operations = [
    ]
