# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-14 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_merge_20180214_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('callcenter', 'Заказ из колл центра'), ('basket', 'Заказ из корзины'), ('oneclick', 'Заказ в один клик')], default='basket', max_length=30),
        ),
    ]
