# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name', 'code'), 'permissions': (('dashboard_access', 'Can access dashboard'),), 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ('-date_created',), 'verbose_name': 'Складская запись', 'verbose_name_plural': 'Складские записи'},
        ),
    ]
