# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_stockrecord_is_our_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='not_delete_stock',
            field=models.BooleanField(default=False, verbose_name='Оставить эти остатки(при выгрузке)?'),
        ),
    ]
