# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basket_vouchers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['date_created', 'pk'], 'verbose_name': 'Строка корзины', 'verbose_name_plural': 'Строки корзины'},
        ),
        migrations.AlterModelOptions(
            name='lineattribute',
            options={'verbose_name': 'Атрибут строки', 'verbose_name_plural': 'Атрибуты строки'},
        ),
    ]
