# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20161201_1036'),
        ('basket', '0003_auto_20161204_2022'),
    ]

    operations = [
    ]
