# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_auto_20170204_1700'),
        ('logistics_exchange', '0002_street'),
        ('basket', '0004_merge_20161206_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.FloatField(default=0.0)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket')),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_exchange.Office')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.UserAddress')),
            ],
        ),
    ]
