# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_deliverybasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybasket',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
