# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_exchange', '0003_officepickpoint'),
        ('basket', '0006_deliverybasket_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybasket',
            name='post_id_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics_exchange.OfficePickPoint'),
        ),
    ]
