# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_deliverybasket_post_id_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybasket',
            name='delivery_time_interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
