# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0099_auto_20171117_1137'),
        ('basket', '0007_deliverybasket_post_id_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineReserveTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_reserve', to='basket.Basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reserve', to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Линии резерва',
                'verbose_name_plural': 'Линии резерва',
            },
        ),
    ]
