# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_linereservetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linereservetime',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='linereservetime',
            name='product',
        ),
        migrations.AddField(
            model_name='linereservetime',
            name='line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lines_reserve', to='basket.Line'),
            preserve_default=False,
        ),
    ]
