# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_deliverybasket_delivery_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverybasket',
            name='delivery_time_interval',
            field=models.CharField(blank=True, choices=[('9-18', '9.00-18.00'), ('9-14', '9.00-14.00'), ('13-18', '13.00-18.00'), ('9-22', '9.00-22.00'), ('18-22', '18.00-22.00 (доп. оплата)')], max_length=50, null=True),
        ),
    ]
