# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20171218_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='linereservetime',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lines_reserve', to='basket.Basket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linereservetime',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='basket.Line'),
        ),
    ]
