# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20171218_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='linereservetime',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время окончания'),
        ),
    ]
