# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0099_auto_20171117_1137'),
        ('basket', '0011_linereservetime_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_reserve', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало резервирования')),
                ('end_reserve', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Конец резервирования')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
            ],
            options={
                'verbose_name': 'Резерв остатков',
                'verbose_name_plural': 'Резерв остатков',
            },
        ),
        migrations.RemoveField(
            model_name='linereservetime',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='linereservetime',
            name='line',
        ),
        migrations.DeleteModel(
            name='LineReserveTime',
        ),
    ]
