# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_stockreserve_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreserve',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
