# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-22 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0016_auto_20171221_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketHistoryReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket')),
            ],
        ),
    ]
