# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_baskethistoryreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskethistoryreserve',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
