# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-25 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0099_auto_20171117_1137'),
        ('basket', '0018_baskethistoryreserve_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldReserveLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Price excl. Tax')),
                ('price_incl_tax', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Price incl. Tax')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_lines', to='basket.Basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_reserve_lines', to='catalogue.Product')),
            ],
        ),
        migrations.AlterModelOptions(
            name='baskethistoryreserve',
            options={'verbose_name': 'Корзина(История резерва)', 'verbose_name_plural': 'Корзина(История резерва)'},
        ),
    ]
