# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0019_auto_20171225_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldreserveline',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
