# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0020_oldreserveline_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldreserveline',
            name='line_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
