# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-19 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20171214_1208'),
        ('basket', '0021_oldreserveline_line_id'),
    ]

    operations = [
    ]
